name: Deploy to staging environment

on:
  push:
    branches:
      - cloudgov/dev

permissions:
  contents: write

jobs:
  deploy:
    environment: dev
    runs-on: ubuntu-latest
    if: ${{ github.event.head_commit.message != 'Merge pull request*' }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: ./.github/actions/setup-project
      - name: Print env name
        run: echo dev
      - name: Vendor dependencies
        run: |
          mkdir -p vendor
          pip download -r requirements.txt --no-binary=:none: -d vendor
          npm install
      - name: Build frontend
        run: |
          npm run build
      - name: Deploy to cloud.gov
        uses: 18f/cg-deploy-action@main
        env:
          OLLAMA_BASE_URL: ${{ secrets.OLLAMA_BASE_URL }}
          WEBUI_NAME: ${{ secrets.WEBUI_NAME }}
          SCARF_NO_ANALYTICS: ${{ secrets.SCARF_NO_ANALYTICS }}
          DO_NOT_TRACK: ${{ secrets.DO_NOT_TRACK }}
          ANONYMIZED_TELEMETRY: ${{ secrets.ANONYMIZED_TELEMETRY }}
          GITHUBLOCAL_CLIENT_ID: ${{ secrets.GITHUBLOCAL_CLIENT_ID }}
          GITHUBLOCAL_CLIENT_SECRET: ${{ secrets.GITHUBLOCAL_CLIENT_SECRET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_GPT35TURBO_DEPLOYMENT_NAME: ${{ secrets.AZURE_OPENAI_GPT35TURBO_DEPLOYMENT_NAME }}
          AZURE_OPENAI_GPT4OMNI_DEPLOYMENT_NAME: ${{ secrets.AZURE_OPENAI_GPT4OMNI_DEPLOYMENT_NAME }}
          WEBUI_SECRET_KEY: ${{ secrets.WEBUI_SECRET_KEY }}
          DEV_ADMIN_EMAILS: ${{ secrets.DEV_ADMIN_EMAILS }}
          DEV_USER_EMAILS: ${{ secrets.DEV_USER_EMAILS }}
          RAG_OPENAI_API_BASE_URL: ${{ secrets.RAG_OPENAI_API_BASE_URL }}
          RAG_OPENAI_API_KEY: ${{ secrets.RAG_OPENAI_API_KEY }}
          RAG_EMBEDDING_ENGINE: ${{ secrets.RAG_EMBEDDING_ENGINE }}
        with:
          cf_username: ${{ secrets.GSAI_GSA_CLOUDGOV_USERNAME }}
          cf_password: ${{ secrets.GSAI_GSA_CLOUDGOV_PASSWORD }}
          cf_org: gsai-gsa
          cf_space: dev
          push_arguments: >-
            --vars-file deploy-config/dev.yml
            --var OLLAMA_BASE_URL="$OLLAMA_BASE_URL"
            --var WEBUI_NAME="$WEBUI_NAME"
            --var SCARF_NO_ANALYTICS="$SCARF_NO_ANALYTICS"
            --var DO_NOT_TRACK="$DO_NOT_TRACK"
            --var ANONYMIZED_TELEMETRY="$ANONYMIZED_TELEMETRY"
            --var GITHUBLOCAL_CLIENT_ID="$GITHUBLOCAL_CLIENT_ID"
            --var GITHUBLOCAL_CLIENT_SECRET="$GITHUBLOCAL_CLIENT_SECRET"
            --var AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
            --var AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
            --var AWS_DEFAULT_REGION="$AWS_DEFAULT_REGION"
            --var AZURE_OPENAI_API_KEY="$AZURE_OPENAI_API_KEY"
            --var AZURE_OPENAI_ENDPOINT="$AZURE_OPENAI_ENDPOINT"
            --var AZURE_OPENAI_GPT35TURBO_DEPLOYMENT_NAME="$AZURE_OPENAI_GPT35TURBO_DEPLOYMENT_NAME"
            --var AZURE_OPENAI_GPT4OMNI_DEPLOYMENT_NAME="$AZURE_OPENAI_GPT4OMNI_DEPLOYMENT_NAME"
            --var WEBUI_SECRET_KEY="$WEBUI_SECRET_KEY"
            --var DEV_ADMIN_EMAILS="$DEV_ADMIN_EMAILS"
            --var DEV_USER_EMAILS="$DEV_USER_EMAILS"
            --var RAG_OPENAI_API_BASE_URL="$RAG_OPENAI_API_BASE_URL"
            --var RAG_OPENAI_API_KEY="$RAG_OPENAI_API_KEY"
            --var RAG_EMBEDDING_ENGINE="$RAG_EMBEDDING_ENGINE"
            --var DEPLOY_ROUTE="gsai-dev"
            --var DEPLOY_ENV="dev"

  bail:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: actions/github-script@v6
        with:
          script: core.setFailed('Checks failed, not deploying')
